services:
  postgres:
    image: postgres:17
    container_name: matchme-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: matchme

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: matchme-backend

    restart: unless-stopped

    ports:
      - "3000:3000"

    env_file:
      - ./backend/.env.docker

    depends_on:
      - postgres

    volumes:
      - ./backend:/app
      - /app/node_modules

    command: sh -c "npx prisma generate && npm run dev"

volumes:
  postgres_data: