import { AppError } from "@/utils/errors/app-error";
import { GoogleGenAI } from "@google/genai";
import { GeminiAnalysisResult } from "../types/gemini-analysis-result";
import { GEMINI_RESPONSE_SCHEMA } from "../constants/gemini/gemini-response-schema";

export class GeminiService {
  private readonly client: GoogleGenAI; 
  private readonly model: string;

  public constructor() {
    const apiKey = process.env.GEMINI_API_KEY; 
    const model = process.env.GEMINI_MODEL;

    if(!apiKey){
      throw new AppError({
        message: "GEMINI API KEY not defined",
        statusCode: 500
      })
    }

    if(!model){
      throw new AppError({
        message: "GEMINI MODEL not defined",
        statusCode: 500
      })
    }
    
    this.client = new GoogleGenAI({
      apiKey: apiKey,
    });

    this.model = model; 
  }

  public async generate(prompt: string): Promise<GeminiAnalysisResult> {
    try {
      const result = await this.client.models.generateContent({
        model: this.model,
        contents: prompt,
        config: {
          responseMimeType: "application/json",
          responseSchema: GEMINI_RESPONSE_SCHEMA
        }
      });

      if (!result.text) {
        throw new AppError({
          message: "No content generated by Gemini",
          statusCode: 500
        })
      }
      
      console.log("Gemini AI generated content", JSON.parse(result.text));
      console.log("Gemini AI tokens used", result.usageMetadata);

      return JSON.parse(result.text) as GeminiAnalysisResult;
      
    } catch (error) {
      throw new AppError({
        message: "Failed to generate content from Gemini",
        statusCode: 500,
      })
    }
  }
}